# Presentations Batch 2024

## Contents

### Part A

- [Civil Engineering and it’s Historical Developments - Dilkaran Singh (2314092 - Presented)](1_Civil_Engineering_And_Historical_Development - Dilkaran Singh(2314092).pdf)
- [Civil Engineering and it’s Historical Developments - Noorprabhdeep Singh (2314063 - Presented)](2_Civil_Engineering_And_Historical_Development.pdf)
- [Imp Of Civil Engineering In Shaping And Impacting The World - Navjot Kaur (2314059 - Presented)](3_Imp_Of_Civil_Engineering_In_Shaping_And_Impacting_The_World.pdf)
- [How Civil Engineering Changed World With Their Work and Innovation - Harshdeep Verma(2314104 - Presented)](4_How_Civil_Engineering_Changed_World_With_Their_Work_and_Innovation.pdf)
- [Ancient and Modern Marvels in Civil Engineering - Vatanveer Singh (2314097 - Presented)](5_Ancient_and_Modern_Marvels_In_Civil_Engineering.pdf)
- [Ancient and Modern Marvels in Civil Engineering - Suryansh Thakur (2314079 - Presented)](6_Ancient_and_Modern_Marvels_In_Civil_Engineering.pdf)
- [Scope Of Work In Various Branches of Civil Engineering and Future Vision - Randeep Singh (2314070 - Presented)](7_Scope_Of_Work_In _Branches of Civil_Engineering_and_Future_Vision.pdf)
- [Recent Civil Engineering Breakthroughs and Innovations - Sahil Insan (2314074 - Presented)](8_Recent_Civil_Engineering_Breakthroughs_and_Innovations.pdf)
- [Entrepreneurial opportunities in civil engineering - Vikrat Bansal (2314094  Presented)](9_Entrepreneurial_opportunities in_Civil _Engineering.pdf)
- [Start-ups_contribute_to_grow_ civil_engineering-Vikas (2314086 - Presented)](10_Start_Ups_Contribute_to_Grow_ Civil_Engineering.pdf)
- [Pre Industrial Days-Sumit Pareek (2314078- Not Presented)](11_Pre_Industrial_Days.pdf)
- [The Industrial Revolution - Udaiveer Singh Sandhu (2314083 -  Presented)](12_The_Industrial_Revolution.pdf)
- [How Agriculture Revolution Help Civil Engineers to Grow - Ravi inder Singh (2314072 - Presented)](13_How_Agriculture_Revolution_Help _Civil_Engineers_to_Grow.pdf)
- [The Agriculture Revolution-Neeraj Singh (2314062- Not Presented)](14_The_Agriculture_Revolution.pdf.pdf)
- [First and Second Industrial Revolutions -Vansh Sehgal (2314084 -  Presented)](15_First_and_Second_Industrial_Revolutions.pdf)
- [First and second industrial revolution - Rajandeep Kaur (2314069 - Not Presented)](16_First_and_Second_Industrial_Revolutions.pdf)
- [IT Revolution and it's Impact on Civil Engineering - Vishal Kumar (2314087  Not Presented)](17_IT_Revolution_and it's Impact_on_Civil_Engineering.pdf)
- [IT Revolution - Navpreet (2314061 - Presented)](18_IT_Revolution.pdf)
- [Ai impact on Civil Engineering - Navneet kaur (2314060 - Presented)](19_AI_in_Civil_Engineering.pdf)
- [Role of IoT in Civil Engineering - Ranvir Singh (2314071- Presented)](20_Role_of_IoT_in_Civil_Engineering.pdf)
- [New Technologies Contributing Civil Engineering - Tushar Gupta (2314082 - Presented)](21_New_Technologies_Contributing_Civil_Engineering.pdf)
- [Civil Engineering In Defense Forces - Vivek singh (2314088 - Not Presented)](22_Civil_Engineering_In_Defense_Forces.pdf)
- [Advances in Bridge Construction And Design-Jagjit Singh (2314103 Not Presented)](23_Advances_in_Bridge_Construction_And_Design.pdf)
- [Building resilience strategies for natural disaster-resistant infrastructure-Vishal Chaudhary(2314089-not Presented)](24_Building_Resilience_Strategies.pdf)
- [Earthquake Resistant Structure - Sukhman singh (2341076 - Not Presented)](25_Earthquake_Resistant_Structure.pdf)
- [Zero Waste Construction - Sukhmandeep singh (2314077 -  Not Presented)](26_Zero_Waste_Construction.pdf)
- [Green Buildings - Binay pal (2314102 - Presented)](27_Green_Buildings.pdf)
- [Environment and Sustainability in Civil Engineering -Yeshmeen kaur (2314090-Presented)](28_Environment_and_Sustainability_in_Civil_Engineering.pdf)
- [Sustainable Development in Civil Engineering - Taranjot Singh  (2314081 -  Not Presented)](29_Sustainable_Development_in_Civil_Engineering.pdf)
- [Role of Civil Engineers in Reducing Global Warming -Mooninder Singh ( 2314057 - Presented) ](30_Role_of_Civil_Engineers_in_Reducing_Global_Warming.pdf)
- [Global Warming its Impact and Possible Causes -peeyanshu sharma (2314066-Presented)](31_Global_Warming_Impact_and_Causes.pdf)
- [Global Warming its Impact and Possible Causes - Tanveer singh (2314096 - Presented)](32_Global_Warming_Impact_and_Causes.pdf)
- [Atmospheric_Pollution - Subham Kumar (2314075 - Presented)](33_Atmospheric_Pollution.pdf)
- [Pollution Mitigation Measures- Mridul Mottan (2314058 - Presented)](34_Pollution_Mitigation_Measures.pdf)
- [Health & Safety aspects for stakeholders - Priyanshu ( 2314067 - Not Presented)](35_Health_and _Safety_Aspects_For_Stakeholders.pdf)
- [Environmental Impact Assessment- Uzair Nazir (2314101 - Presented)](36_Environmental_Impact_Assessment.pdf)
- [Environment impact assessment - Pawandeep kaur ( 2314065- Presented)](37_Environmental Impact_Assessment.pdf)
- [Innovations and Methodologies For Ensuring Sustainability - Taranjeet Kaur (2314080 - Presented)](38_Innovations_and_Methodologies_For_Ensuring_Sustainability.pdf)
- [Renewable Energy Integration in Civil Engineering - Zorawar Singh (2314091 - Presented)
](39_Renewable_Energy_Integration_in Civil_Engineering.pdf)
